# Name of workflow
name: brain-games CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:
      - name: npm install, build
        # Install and build project
        run: 
          make install
        
      - name: Run linter
        # Run Linter
        run: 
          make lint
      